title: 3(r)D Point
description: Drukowane 3d brajlowskie oznaczenia dla osób niewidomych
lang: pl-PL
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one